# Most of config is pulled from: https://github.com/numToStr/dotfiles/blob/master/tmux/.config/tmux/tmux.conf

# Additionaly if you want to rebind some tmux keys and get rid off 'Prefix key' in some operations check this repo and the article:
# https://github.com/zserge/dotfiles/blob/master/.tmux.conf
# https://zserge.com/posts/tmux/

# Below tmux settings does the following
# - Setting the correct terminal for tmux
# - IDK how, but this allows strikethrough text with highlights
set -g default-terminal "${TERM}"
set-option -a terminal-features "${TERM}:RGB"

set -g mouse on # enable mouse mode (tmux 2.1 and above)

set -g mode-keys vi # vi is good
set -g status-keys emacs # emacs key bindings in tmux command prompt

set -g base-index 1         # starting window numbered 1
set -g pane-base-index 1    # starting pane numbered 1
set -g renumber-windows on  # renumber windows when one is closed

set -g set-titles on # enable dynamic title
set -g set-titles-string '#S #I::#W' # dynamic title format

set -s escape-time 0 # address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g history-limit 50000 # increase scrollback buffer size
set -g display-time 3000 # display messages for 3 seconds
set -g focus-events on # focus events enabled for terminals that support them
setw -g aggressive-resize on # super useful when using "grouped sessions" and multi-monitor setup

# source .tmux.conf as suggested in `man tmux`
bind R source-file "${HOME}/.config/tmux/tmux.conf" \; display-message 'Config reloaded!'
